"""Adiciona coluna foto_perfil ao usuário

Revision ID: 77bff94b5cb1
Revises: 26c35b054cdb
Create Date: 2025-01-19 22:36:39.171100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77bff94b5cb1'
down_revision = '26c35b054cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')

    # ### end Alembic commands ###
