"""Adicionando biografia e curso ao modelo Usuario

Revision ID: 26c35b054cdb
Revises: 
Create Date: 2025-01-19 18:38:17.589063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c35b054cdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biografia', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('curso', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('curso')
        batch_op.drop_column('biografia')

    # ### end Alembic commands ###
